@{
    ModuleVersion = '0.1.0'
    GUID = 'd2fdbd3a-f5d3-4f5e-9d12-123456789abc'
    Author = 'Generated by M365TenantMigration'
    CompanyName = 'YourCompany'
    Copyright = '(c) 2026'
    Description = 'Module to export and import global Microsoft 365 / Entra ID tenant configuration.'
    PowerShellVersion = '7.2'
    FunctionsToExport = @('Export-M365TenantConfiguration','Import-M365TenantConfiguration')
    RequiredModules = @('Microsoft.Graph')
    DefaultCommandPrefix = 'M365TenantMigration'
}
